const MEETING_EVENT_CREATE = 'MEETING_EVENT_CREATE';
const MEETING_EVENT_JOIN = 'MEETING_EVENT_JOIN';
const MEETING_EVENT_LEAVE = 'MEETING_EVENT_LEAVE';
const MEETING_EVENT_END = 'MEETING_EVENT_END';
const MEETING_EVENT_MUTE = 'MEETING_EVENT_MUTE';
const MEETING_EVENT_UNMUTE = 'MEETING_EVENT_UNMUTE';
const MEETING_EVENT_SCREEN_SHARE = 'MEETING_EVENT_SCREEN_SHARE';
const MEETING_EVENT_STOP_SCREEN_SHARE = 'MEETING_EVENT_STOP_SCREEN_SHARE';
const MEETING_EVENT_ERROR = 'MEETING_EVENT_ERROR';

module.exports = {
    MEETING_EVENT_CREATE,
    MEETING_EVENT_JOIN,
    MEETING_EVENT_LEAVE,
    MEETING_EVENT_END,
    MEETING_EVENT_MUTE,
    MEETING_EVENT_UNMUTE,
    MEETING_EVENT_SCREEN_SHARE,
    MEETING_EVENT_STOP_SCREEN_SHARE,
    MEETING_EVENT_ERROR
};